---
name: Dependabot CI
on:
  pull_request_target:

jobs:
  dependabot_ci:
    name: Dependabot CI
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Build and test
        run: ./gradlew build --info --no-daemon

      - name: Fetch PR metadata
        uses: dependabot/fetch-metadata@v1.3.3
        id: dependabot-metadata
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Merge PR
        run: gh pr merge --auto --squash "$PR_URL"
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
