---
name: Lint Code Base
on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
    branches:
      - "master"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # can be removed if VALIDATE_ALL_CODEBASE = true

      - name: Lint
        uses: oxsecurity/megalinter/flavors/java@v6.22.2 # see https://megalinter.io/flavors/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false  # Lint only changed files
          # other configurations are found in .mega-linter.yml

      - name: Upload reports
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log
